import type { PunchingShearInput, PunchingShearReportModel, PunchingShearResult } from './types'

export function buildPunchingShearReport(
  input: PunchingShearInput,
  result: PunchingShearResult,
): PunchingShearReportModel {
  return {
    title: 'Punching Shear Draft Center Check',
    standard: 'СП63.13330 - draft verification pending',
    caseType: input.caseType,
    inputSummary: {
      caseType: input.caseType,
      axialForceKn: input.forces.axialForceKn,
      momentXKnM: input.forces.momentXKnM,
      momentYKnM: input.forces.momentYKnM,
      concreteClass: input.concrete.className,
      slabThicknessMm: input.slab.thicknessMm,
      openingsCount: input.openings.length,
      shearReinforcementEnabled: input.shearReinforcement.enabled,
    },
    resultSummary: {
      status: result.status,
      utilization: result.utilizationRatio,
      perimeterMm: result.controlPerimeterMm,
      effectiveDepthMm: result.effectiveDepthMm,
      passed: result.passed === null ? 'not evaluated' : String(result.passed),
      maxShearStressMpa: result.maxShearStressMpa,
      minShearStressMpa: result.minShearStressMpa,
    },
    geometrySummary: {
      perimeterMm: result.perimeter.perimeterMm,
      effectiveDepthMm: result.perimeter.effectiveDepthMm,
      draftOffsetMm: result.perimeter.draftOffsetMm,
      vertexCount: result.perimeter.vertices.length,
      segmentCount: result.perimeter.segments.length,
      boundingBoxWidthMm: result.perimeter.boundingBox.width,
      boundingBoxHeightMm: result.perimeter.boundingBox.height,
    },
    segments: result.perimeter.segments.map((segment) => ({
      id: segment.id,
      kind: segment.kind,
      startX: segment.start.x,
      startY: segment.start.y,
      endX: segment.end.x,
      endY: segment.end.y,
      lengthMm: segment.lengthMm,
    })),
    svgMetadata: {
      viewBoxWidth: result.svgModel.viewBox.width,
      viewBoxHeight: result.svgModel.viewBox.height,
      elementCount: result.svgModel.elements.length,
      scaleMode: result.svgModel.metadata.scaleMode,
      stressDiagram: result.svgModel.metadata.stressDiagram,
    },
    formulaSummary: [
      'DRAFT / NOT FOR DESIGN USE',
      'v = N / (u * h0)',
      'N = design shear force',
      'u = control perimeter',
      'h0 = effective depth',
      'DRAFT moment redistribution: v(point) = vbase * (1 + ex*x/rx^2 + ey*y/ry^2)',
    ],
    calculationValues: {
      N: result.designShearForceN,
      u: result.controlPerimeterMm,
      h0: result.effectiveDepthMm,
      v: result.shearStressMpa,
      vmax: result.maxShearStressMpa,
      vmin: result.minShearStressMpa,
      R: result.draftConcreteResistanceMpa,
      utilization: result.utilizationRatio,
      passed: result.passed,
    },
    momentTransferSummary: {
      enabled: result.momentTransferEnabled,
      status: result.momentTransfer.status,
      Mx: result.momentTransfer.momentXKnM,
      My: result.momentTransfer.momentYKnM,
      eccentricityX: result.eccentricityX,
      eccentricityY: result.eccentricityY,
      maxStressMpa: result.maxShearStressMpa,
      minStressMpa: result.minShearStressMpa,
      formulasVerified: result.stressDiagramMetadata?.formulasVerified ?? false,
    },
    stressDistributionSummary: {
      status: result.stressDistribution?.status ?? 'disabled',
      pointCount: result.stressDistribution?.points.length ?? 0,
      segmentCount: result.stressDistribution?.segmentStresses.length ?? 0,
      baseStressMpa: result.stressDistribution?.baseStressMpa ?? result.shearStressMpa,
      method: result.stressDiagramMetadata?.method ?? 'draft-linear-perimeter-redistribution',
    },
    warnings: result.warnings,
    calculationSteps: [
      'DRAFT / NOT FOR DESIGN USE.',
      'Input schema validation completed.',
      'Units normalized into the current internal DTO shape.',
      'Draft material resistance selected.',
      'Control perimeter draft geometry generated.',
      'SVG sketch model generated from geometry DTOs.',
      'Draft moment-transfer stress distribution generated where Mx/My are present.',
      'Draft center force-only check evaluated where supported.',
      'Openings, slab edges, and shear reinforcement intentionally skipped.',
    ],
  }
}
