import type { PunchingShearInput, PunchingShearReportModel, PunchingShearResult } from './types'
import { buildPunchingShearTrace } from './trace/traceBuilder'
import { defaultAxisConvention } from './verification/axisConvention'
import { createStressDistributionChecksum } from './verification/stressDistributionComparison'

export function buildPunchingShearReport(
  input: PunchingShearInput,
  result: PunchingShearResult,
): PunchingShearReportModel {
  const calculationTrace = buildPunchingShearTrace(input, result)

  return {
    title: 'Расчет на продавливание',
    standard: 'СП 63.13330 - статус зависит от verificationStatus результата',
    caseType: input.caseType,
    inputSummary: {
      caseType: input.caseType,
      axialForceKn: input.forces.axialForceKn,
      momentXKnM: input.forces.momentXKnM,
      momentYKnM: input.forces.momentYKnM,
      concreteClass: input.concrete.className,
      slabThicknessMm: input.slab.thicknessMm,
      openingsCount: input.openings.length,
      shearReinforcementEnabled: input.shearReinforcement.enabled,
    },
    resultSummary: {
      status: result.status,
      utilization: result.governingUtilization,
      perimeterMm: result.controlPerimeterMm,
      effectiveDepthMm: result.effectiveDepthMm,
      passed: result.passed === null ? 'не оценено' : String(result.passed),
      maxShearStressMpa: result.maxShearStressMpa,
      minShearStressMpa: result.minShearStressMpa,
    },
    geometrySummary: {
      perimeterMm: result.perimeter.perimeterMm,
      effectiveDepthMm: result.perimeter.effectiveDepthMm,
      draftOffsetMm: result.perimeter.draftOffsetMm,
      vertexCount: result.perimeter.vertices.length,
      segmentCount: result.perimeter.segments.length,
      boundingBoxWidthMm: result.perimeter.boundingBox.width,
      boundingBoxHeightMm: result.perimeter.boundingBox.height,
    },
    roundGeometrySummary: {
      enabled: input.caseType === 'round',
      diameterMm: input.roundColumn?.diameterMm ?? 'н/д',
      position: input.roundColumn?.position ?? 'н/д',
      slabThicknessMm: input.roundColumn?.slabThickness ?? input.slab.thicknessMm,
      effectiveDepthMm: input.roundColumn?.effectiveDepth ?? input.slab.effectiveDepthMm,
      coverMm: input.roundColumn?.cover ?? input.slab.concreteCoverMm,
      controlPerimeterMm: result.perimeter.perimeterMm,
      segmentCount: result.perimeter.segments.length,
      draftFormula: 'v = N / (u * h0)',
      applicability: 'draft-only',
      warningCount: result.perimeter.warnings.length,
    },
    wallGeometrySummary: {
      enabled: input.caseType === 'wall-end',
      wallLengthMm: input.wall?.wallLength ?? 'н/д',
      wallThicknessMm: input.wall?.wallThickness ?? 'н/д',
      slabThicknessMm: input.wall?.slabThickness ?? input.slab.thicknessMm,
      effectiveDepthMm: input.wall?.effectiveDepth ?? input.slab.effectiveDepthMm,
      coverMm: input.wall?.cover ?? input.slab.concreteCoverMm,
      controlPerimeterMm: result.perimeter.perimeterMm,
      warningCount: result.perimeter.warnings.length,
    },
    wallCornerGeometrySummary: {
      enabled: input.caseType === 'wall-corner',
      wallLengthXMm: input.wallCorner?.wallLengthX ?? 'н/д',
      wallLengthYMm: input.wallCorner?.wallLengthY ?? 'н/д',
      wallThicknessXMm: input.wallCorner?.wallThicknessX ?? 'н/д',
      wallThicknessYMm: input.wallCorner?.wallThicknessY ?? 'н/д',
      orientation: input.wallCorner?.orientation ?? 'н/д',
      controlPerimeterMm: result.perimeter.perimeterMm,
      applicability: 'draft-only',
      warningCount: result.perimeter.warnings.length,
    },
    boundaryEffectsSummary: {
      edgeAffected: result.perimeter.edgeAffected,
      cornerAffected: result.perimeter.cornerAffected,
      removedPerimeterMm: result.perimeter.removedPerimeterMm,
      clippedPerimeterMm: result.perimeter.clippedPerimeterMm,
    },
    openingsSummary: {
      openingCount: input.openings.length,
      openingAffected: result.perimeter.openingAffected,
      affectedOpeningCount: result.perimeter.clippingMetadata.affectedOpeningIds.length,
      removedSegments: result.perimeter.removedSegments.filter((segment) => segment.removedBy === 'opening').length,
      openingTangents: result.perimeter.openingTangents.length,
    },
    geometryVerificationSummary: {
      clippedPerimeterMm: result.perimeter.clippedPerimeterMm,
      removedPerimeterMm: result.perimeter.removedPerimeterMm,
      removedSegments: result.perimeter.removedSegments.length,
      tangentCount: result.perimeter.openingTangents.length,
      openingAffected: result.perimeter.openingAffected,
      boundaryClassification: result.perimeter.clippingMetadata.boundaryCondition,
    },
    multipleControlPerimetersSummary: result.contourComparison.map((contour) => ({
      contourId: contour.contourId,
      offsetMm: contour.offsetMm,
      perimeterMm: contour.perimeterMm,
      draftStressMpa: contour.draftStressMpa,
      utilization: contour.utilization,
      selected: contour.selected,
      warnings: contour.warnings.join('; ') || 'нет',
    })),
    shearReinforcementSummary: {
      enabled: result.shearReinforcement.enabled,
      steelClass: result.shearReinforcement.steelClass ?? 'н/д',
      layoutType: result.shearReinforcement.layoutType ?? 'н/д',
      barDiameterMm: result.shearReinforcement.barDiameterMm,
      simpleBarCount: result.shearReinforcement.simpleBarCount,
      barSpacingMm: result.shearReinforcement.barSpacingMm,
      rowCount: result.shearReinforcement.rowCount,
      legsPerRow: result.shearReinforcement.legsPerRow,
      totalLegs: result.shearReinforcement.totalLegs,
      firstRowDistanceMm: result.shearReinforcement.firstRowDistanceMm,
      rowSpacingMm: result.shearReinforcement.rowSpacingMm,
      reinforcementAreaMm2: result.reinforcementAreaMm2,
      reinforcementContributionN: result.reinforcementContributionN,
      draftCapacityWithReinforcementN: result.draftCapacityWithReinforcementN,
      utilizationWithReinforcement: result.utilizationWithReinforcement,
      warnings: result.reinforcementWarnings.join('; ') || 'нет',
    },
    segments: result.perimeter.segments.map((segment) => ({
      id: segment.id,
      kind: segment.kind,
      startX: segment.start.x,
      startY: segment.start.y,
      endX: segment.end.x,
      endY: segment.end.y,
      lengthMm: segment.lengthMm,
    })),
    svgMetadata: {
      viewBoxWidth: result.svgModel.viewBox.width,
      viewBoxHeight: result.svgModel.viewBox.height,
      elementCount: result.svgModel.elements.length,
      scaleMode: result.svgModel.metadata.scaleMode,
      stressDiagram: result.svgModel.metadata.stressDiagram,
    },
    formulaSummary: [
      'ЧЕРНОВИК / НЕ ДЛЯ ПРОЕКТНОГО ПРИМЕНЕНИЯ',
      'v = N / (u * h0)',
      'N = расчетная поперечная сила',
      'u = контрольный периметр',
      'h0 = рабочая высота',
      'ЧЕРНОВОЕ перераспределение моментов: v(point) = vbase * (1 + ex*x/rx^2 + ey*y/ry^2)',
      'ЧЕРНОВОЙ выбор нескольких контуров: вычислить v = N / (u * h0) по каждому контуру и выбрать максимальное использование',
      'ЧЕРНОВАЯ поперечная арматура: Vsw = Asw,total * Rsw,draft',
    ],
    calculationValues: {
      N: result.designShearForceN,
      u: result.controlPerimeterMm,
      h0: result.effectiveDepthMm,
      v: result.shearStressMpa,
      vmax: result.maxShearStressMpa,
      vmin: result.minShearStressMpa,
      R: result.draftConcreteResistanceMpa,
      utilization: result.governingUtilization,
      utilizationConcrete: result.utilizationConcrete,
      utilizationTotal: result.utilizationTotal,
      governingUtilization: result.governingUtilization,
      concreteCapacityN: result.concreteCapacityN,
      totalCapacityN: result.totalCapacityN,
      reinforcementAreaMm2: result.reinforcementAreaMm2,
      reinforcementContributionN: result.reinforcementContributionN,
      draftCapacityWithReinforcementN: result.draftCapacityWithReinforcementN,
      utilizationWithReinforcement: result.utilizationWithReinforcement,
      passed: result.passed,
    },
    momentTransferSummary: {
      enabled: result.momentTransferEnabled,
      status: result.momentTransfer.status,
      Mx: result.momentTransfer.momentXKnM,
      My: result.momentTransfer.momentYKnM,
      eccentricityX: result.eccentricityX,
      eccentricityY: result.eccentricityY,
      maxStressMpa: result.maxShearStressMpa,
      minStressMpa: result.minShearStressMpa,
      formulasVerified: result.stressDiagramMetadata?.formulasVerified ?? false,
    },
    stressDistributionSummary: {
      status: result.stressDistribution?.status ?? 'disabled',
      pointCount: result.stressDistribution?.points.length ?? 0,
      segmentCount: result.stressDistribution?.segmentStresses.length ?? 0,
      baseStressMpa: result.stressDistribution?.baseStressMpa ?? result.shearStressMpa,
      method: result.stressDiagramMetadata?.method ?? 'draft-linear-perimeter-redistribution',
    },
    stressRegressionSummary: {
      checksum: createStressDistributionChecksum(result.stressDistribution),
      driftDetected: 'нет ожидаемого базиса',
      expectedVsActual: 'ожидаются доверенные доказательства по напряжениям',
      tolerance: 'не применяется до заполнения ожидаемых значений',
      regressionStatus: result.stressDistribution ? 'draft-placeholder' : 'disabled',
    },
    axisConventionSummary: {
      xPositiveDirection: defaultAxisConvention.xPositiveDirection,
      yPositiveDirection: defaultAxisConvention.yPositiveDirection,
      momentXSignConvention: defaultAxisConvention.momentXSignConvention,
      momentYSignConvention: defaultAxisConvention.momentYSignConvention,
      traversal: defaultAxisConvention.traversal,
    },
    sp63InteractionSummary: {
      available: result.sp63Interaction !== null,
      label: result.sp63Interaction
        ? 'Кандидат бенчмарка взаимодействия СП 63 на основе фикстуры Mathcad'
        : 'недоступно',
      benchmarkStatus: result.sp63Interaction?.benchmarkStatus ?? 'не оценено',
      RbtMpa: result.sp63Interaction?.Rbt ?? null,
      RswMpa: result.sp63Interaction?.Rsw ?? null,
      contourAM: result.sp63Interaction?.a ?? null,
      contourBM: result.sp63Interaction?.b ?? null,
      perimeterM: result.sp63Interaction?.u ?? null,
      areaM2: result.sp63Interaction?.Ab ?? null,
      WxM2: result.sp63Interaction?.Wx ?? null,
      WyM2: result.sp63Interaction?.Wy ?? null,
      FbUltKn: result.sp63Interaction?.FbUlt ?? null,
      MxBUltKnM: result.sp63Interaction?.MxBUlt ?? null,
      MyBUltKnM: result.sp63Interaction?.MyBUlt ?? null,
      sw1Mm: result.sp63Interaction?.sw1 ?? null,
      swMm: result.sp63Interaction?.sw ?? null,
      nw: result.sp63Interaction?.nw ?? null,
      AswCm2: result.sp63Interaction?.Asw ?? null,
      qswKnPerM: result.sp63Interaction?.qsw ?? null,
      FswUltKn: result.sp63Interaction?.FswUlt ?? null,
      FultKn: result.sp63Interaction?.Fult ?? null,
      MxUltKnM: result.sp63Interaction?.MxUlt ?? null,
      MyUltKnM: result.sp63Interaction?.MyUlt ?? null,
      FKn: result.sp63Interaction?.F ?? null,
      MxKnM: result.sp63Interaction?.Mx ?? null,
      MyKnM: result.sp63Interaction?.My ?? null,
      utilizationConcreteOnly: result.sp63Interaction?.utilizationConcreteOnly ?? null,
      forceCapConcreteOnly: result.sp63Interaction?.forceCapConcreteOnly ?? null,
      utilizationWithReinforcement: result.sp63Interaction?.utilizationWithReinforcement ?? null,
      outerContourUtilization: result.sp63Interaction?.outerContour?.utilization ?? null,
    },
    verificationCapabilities: {
      verified: result.verifiedFeatures,
      draft: result.draftFeatures,
    },
    verificationEvidence: result.verificationEvidence,
    warnings: [
      ...result.warnings,
      ...result.contourWarnings,
    ],
    calculationTrace,
    calculationSteps: [
      'ЧЕРНОВИК / НЕ ДЛЯ ПРОЕКТНОГО ПРИМЕНЕНИЯ.',
      'Проверка исходных данных завершена.',
      'Единицы измерения приведены к расчетной модели.',
      'Выбрано черновое сопротивление материала.',
      'Черновая геометрия контрольного периметра построена.',
      input.caseType === 'round'
        ? 'Черновая геометрия круглой центральной колонны построена без проверки круглых колонн по СП 63.'
        : 'Геометрия круглой колонны не выбрана.',
      input.caseType === 'wall-end'
        ? 'Черновая геометрия конца стены построена без коэффициентов продавливания стен по СП 63.'
        : 'Геометрия конца стены не выбрана.',
      input.caseType === 'wall-corner'
        ? 'Черновая геометрия угла стены построена без коэффициентов продавливания стен по СП 63.'
        : 'Геометрия угла стены не выбрана.',
      'Схема геометрии построена по расчетным данным.',
      'Черновое распределение напряжений от передачи моментов построено там, где заданы Mx/My.',
      'Черновая проверка прямоугольной колонны только от силы выполнена там, где поддерживается.',
      result.controlContours.length > 0
        ? 'Сформированы несколько черновых контрольных контуров; критический черновой контур выбран по максимальному коэффициенту использования.'
        : 'Несколько черновых контрольных контуров отключены.',
      'Черновая геометрия отверстий и обрезки по краям плиты построена там, где задана.',
      result.shearReinforcement.enabled
        ? 'Черновые площадь, вклад, несущая способность и использование поперечной арматуры построены для инженерного просмотра.'
        : 'Поперечная арматура отключена.',
    ],
  }
}
