import type { PunchingShearInput, PunchingShearResult } from '../types'
import { traceFoundationReference } from './traceMetadata'
import { formatEnabled, formatNullable } from './traceFormat'
import type { TraceSection } from './traceSection'

export function traceForMultipleContours(
  input: PunchingShearInput,
  result: PunchingShearResult,
): TraceSection | null {
  if (!input.multipleContours?.enabled) {
    return null
  }

  const warnings = [
    'Multiple contour selection is draft-only and requires SP63 verification.',
    ...result.contourWarnings,
  ]

  return {
    id: 'multiple-contours-trace',
    title: 'Multiple Contours Trace',
    steps: [
      {
        id: 'contour-generation',
        title: 'Contour generation',
        description: 'Multiple control contours are generated by the current draft contour workflow.',
        formula: 'multipleContours DTO -> draft control contours',
        substitutedFormula: `enabled = ${formatEnabled(input.multipleContours.enabled)}, count = ${input.multipleContours.count}`,
        result: `${result.controlContours.length} contour(s)`,
        units: 'n/a',
        sourceType: 'draft',
        sourceReference: traceFoundationReference,
        warnings,
      },
      {
        id: 'contour-offsets',
        title: 'Contour offsets',
        description: 'Offsets are reported from generated contour DTOs.',
        formula: 'offset_i = configured draft offset sequence',
        substitutedFormula: `step = ${input.multipleContours.offsetStep}`,
        result: result.controlContours.map((contour) => `${contour.id}:${formatNullable(contour.offsetMm)}`).join(', '),
        units: 'mm',
        sourceType: 'draft',
        sourceReference: traceFoundationReference,
        warnings,
      },
      {
        id: 'draft-stress-per-contour',
        title: 'Draft stress per contour',
        description: 'Each contour stress is current draft stress, used only for comparison.',
        formula: 'v_i = N / (u_i * h0)',
        substitutedFormula: `${result.contourComparison.length} comparison row(s)`,
        result: result.contourComparison.map((row) => `${row.contourId}:${formatNullable(row.draftStressMpa, 6)}`).join(', '),
        units: 'MPa',
        sourceType: 'draft',
        sourceReference: traceFoundationReference,
        warnings,
      },
      {
        id: 'draft-critical-contour-selection',
        title: 'Draft critical contour selection',
        description: 'Critical contour is selected by the current draft maximum-utilization rule.',
        formula: 'critical = max(eta_i)',
        substitutedFormula: `selected = ${result.selectedContourId ?? 'none'}`,
        result: result.draftCriticalContour?.selectedContourId ?? 'none',
        units: 'n/a',
        sourceType: 'draft',
        sourceReference: traceFoundationReference,
        warnings,
      },
      {
        id: 'contour-warnings',
        title: 'Contour warnings',
        description: 'Warnings are surfaced from draft contour generation and selection.',
        formula: 'warnings = contourWarnings',
        substitutedFormula: `${result.contourWarnings.length} warning(s)`,
        result: result.contourWarnings.join('; ') || 'none',
        units: 'n/a',
        sourceType: 'draft',
        sourceReference: traceFoundationReference,
        warnings,
      },
    ],
  }
}
